### ISSUE TITLE
npm install --save indy-sdk command issue

### ISSUE THREAD

**Issue by SathyaVelmurugan** [Picolab/indy-sdk#5]
c:\users\admin\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'A0' to 'double', possible loss of data [C:\Users\Admin\node_module
s\indy-sdk\build\indynodejs.vcxproj]
          with
          [
              A0=unsigned __int64
          ] (compiling source file ..\src\indy.cc)
  c:\users\admin\node_modules\indy-sdk\src\indy.cc(248): note: see reference to
   function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,u
  nsigned __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
LINK : warning LNK4044: unrecognized option '/LC:\Users\Admin\node_modules\indy
-sdk.lib'; ignored [C:\Users\Admin\node_modules\indy-sdk\build\indynodejs.vcxpr
oj]
LINK : fatal error LNK1181: cannot open input file '.lib' [C:\Users\Admin\node_
modules\indy-sdk\build\indynodejs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Build
Tools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\npm\no
de_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)

**Comment by SathyaVelmurugan** [comment]
PS C:\Users\Admin\my-first-app> npm install --save --msvs_version=2013 indy-sdk

> indy-sdk@1.6.2 install C:\Users\Admin\my-first-app\node_modules\indy-sdk
> node-gyp rebuild


C:\Users\Admin\my-first-app\node_modules\indy-sdk>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node
_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Admin\my-first-app\node_modules\indy-sdk\build\indynodejs.vcxproj(20,3): error MSB4019: The imported project "
C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that t
he file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
62:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Admin\my-first-app\node_modules\indy-sdk
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN my-first-app@1.0.0 No description
npm WARN my-first-app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indy-sdk@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indy-sdk@1.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-10-25T07_35_09_559Z-debug.log

**Comment by farskipper** [comment]
I'm not a windows dev, so we're at my limits. But here are some things that might help in debugging this.

https://github.com/nodejs/node-gyp is the build tool that sets this up.

Be sure to read and follow the instructions on setting this up for Windows:
https://github.com/nodejs/node-gyp#on-windows

If that doesn't help, try googling "node-gyp Microsoft.Cpp.Default.props was not found"

As always, feel free to delete the node_modules folder so you have a clean slate before doing the install again. (C:\Users\Admin\my-first-app\node_modules)
